# generated by running rails generate migration AddAmountPaidToOrders amount_paid:decimal
class AddAmountPaidToOrders < ActiveRecord::Migration
  def change
    add_column :orders, :amount_paid, :decimal
  end
end
